# Explore here

In [54]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


In [55]:
#Vamos a partir abriendo el dataset y haciendo el EDA correspondiente 
df=pd.read_csv("https://raw.githubusercontent.com/4GeeksAcademy/naive-bayes-project-tutorial/main/playstore_reviews.csv")
df.head(5)

package_name                                             review  \
0  com.facebook.katana   privacy at least put some option appear offli...   
1  com.facebook.katana   messenger issues ever since the last update, ...   
2  com.facebook.katana   profile any time my wife or anybody has more ...   
3  com.facebook.katana   the new features suck for those of us who don...   
4  com.facebook.katana   forced reload on uploading pic on replying co...   

   polarity  
0         0  
1         0  
2         0  
3         0  
4         0

In [56]:
#pasamos todos los comentarios a minusculas
df["review"]=df["review"].str.strip().str.lower()
df["review"]


0      privacy at least put some option appear offlin...
1      messenger issues ever since the last update, i...
2      profile any time my wife or anybody has more t...
3      the new features suck for those of us who don'...
4      forced reload on uploading pic on replying com...
                             ...                        
886    loved it i loooooooooooooovvved it because it ...
887    all time legendary game the birthday party lev...
888    ads are way to heavy listen to the bad reviews...
889    fun works perfectly well. ads aren't as annoyi...
890    they're everywhere i see angry birds everywher...
Name: review, Length: 891, dtype: object

In [57]:
from sklearn.feature_extraction.text import CountVectorizer
vec_model=CountVectorizer(stop_words="english")
vec_model.fit(df["review"])
vec_model.get_feature_names_out


<bound method CountVectorizer.get_feature_names_out of CountVectorizer(stop_words='english')>

In [67]:
#ahora vamos a hacer los x e y de test y train con train testsplit 
#todo esto antes de transformar los datos
from sklearn.model_selection import train_test_split
X=df["review"]
y=df["polarity"]
X_train,X_test,y_train,y_test=train_test_split(X, y , test_size=0.2 , random_state=42)

In [68]:
X_train =vec_model.fit_transform(X_train).toarray()
X_test=vec_model.transform(X_test).toarray()


In [71]:
from sklearn.naive_bayes import MultinomialNB,GaussianNB,BernoulliNB

In [ ]:
#entrenamos los distintos modelos para uego compararlos.
multinominal_model=MultinomialNB()
Gaussian_model=GaussianNB()
Bernoulli_model=BernoulliNB()
multinominal_model.fit(X_train,y_train)
Gaussian_model.fit(X_train,y_train)
Bernoulli_model.fit(X_train,y_train)
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
y_pred_multinominal=multinominal_model.predict(X_test)
y_pred_Gaussian=Gaussian_model.predict(X_test)
y_pred_Bernoulli=Bernoulli_model.predict(X_test)




In [ ]:
#calculamos las accuracies de los distintos tipos de tests.
accu_multinominal=accuracy_score(y_test,y_pred_multinominal)
accu_Gaussian=accuracy_score(y_test,y_pred_Gaussian)
accu_Bernoulli=accuracy_score(y_test,y_pred_Bernoulli)
print("Accuracy Multinomial:", accu_multinominal)
print("Accuracy Gaussian:", accu_Gaussian)
print("Accuracy Bernoulli:", accu_Bernoulli)


Accuracy Multinomial: 0.8156424581005587
Accuracy Gaussian: 0.8044692737430168
Accuracy Bernoulli: 0.770949720670391


In [79]:
#matriz de conficion de los distintos modelos
confusion_multinominal=confusion_matrix(y_test,y_pred_multinominal)
confusion_Gaussian=confusion_matrix(y_test,y_pred_Gaussian)
confusion_Bernoulli=confusion_matrix(y_test,y_pred_Bernoulli)
print("Confusion Matrix Multinomial:\n", confusion_multinominal)
print("Confusion Matrix Gaussian:\n", confusion_Gaussian)
print("Confusion Matrix Bernoulli:\n", confusion_Bernoulli)



Confusion Matrix Multinomial:
 [[114  12]
 [ 21  32]]
Confusion Matrix Gaussian:
 [[111  15]
 [ 20  33]]
Confusion Matrix Bernoulli:
 [[117   9]
 [ 32  21]]


In [81]:
reporte_multinominal=classification_report(y_test,y_pred_multinominal)
reporte_gaussian=classification_report(y_test,y_pred_Gaussian)
reporte_bernoulli=classification_report(y_test,y_pred_Bernoulli)
print("Classification Report Multinomial:\n", reporte_multinominal)
print("Classification Report Gaussian:\n", reporte_gaussian)
print("Classification Report Bernoulli:\n", reporte_bernoulli)




Classification Report Multinomial:
               precision    recall  f1-score   support

           0       0.84      0.90      0.87       126
           1       0.73      0.60      0.66        53

    accuracy                           0.82       179
   macro avg       0.79      0.75      0.77       179
weighted avg       0.81      0.82      0.81       179

Classification Report Gaussian:
               precision    recall  f1-score   support

           0       0.85      0.88      0.86       126
           1       0.69      0.62      0.65        53

    accuracy                           0.80       179
   macro avg       0.77      0.75      0.76       179
weighted avg       0.80      0.80      0.80       179

Classification Report Bernoulli:
               precision    recall  f1-score   support

           0       0.79      0.93      0.85       126
           1       0.70      0.40      0.51        53

    accuracy                           0.77       179
   macro avg       0.74  

finalmente podemos notar que el multinominal es le mejor modelo en este caso. gracias a que tiene mejor accuracy y el porcentaje de aciertos en ambas categorias es mas o menos parejo.


In [82]:
from pickle import dump
dump(Gaussian_model,open("../models/Gaussian_model.pkl","wb"))
dump(multinominal_model,open("../models/multinominal_model.pkl","wb"))
dump(Bernoulli_model,open("../models/Bernoulli_model.pkl","wb"))